package com.gcexe.monitor.persistence.dao;

import java.util.List;
import java.util.Map;

import com.gcexe.monitor.persistence.entity.SysIP;

public interface SysIPMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int insert(SysIP record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int insertSelective(SysIP record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	SysIP selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int updateByPrimaryKeySelective(SysIP record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(SysIP record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int updateByPrimaryKey(SysIP record);

	public List<SysIP> search(Map<String,Object> map);
    
    /**
	 * IP(域名�?)TOP10
	 */
	public List  domainCnt();
	/**
	 * 非法域名IPTOP10
	 */
	public List  illegalcnt();
	/**
	 * IP域名总数/非法域名总数态势
	 */
	public List  situation();
	/**
	 * IP域名总数/非法域名总数
	 */
	public List  count();
	/**
	 * IP平均挂域名�?�势
	 */
	public List  avgsituation();
    
    
    
    
    
}