package com.gcexe.monitor.persistence.dao;

import java.util.List;
import java.util.Map;

import com.gcexe.monitor.persistence.entity.SysIP;
import com.gcexe.monitor.persistence.statistics.entity.IPCntStatis;
import com.gcexe.monitor.persistence.statistics.entity.IPTopStatis;

public interface SysIPMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int insert(SysIP record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int insertSelective(SysIP record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	SysIP selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int updateByPrimaryKeySelective(SysIP record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(SysIP record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_ip
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	int updateByPrimaryKey(SysIP record);

	public List<SysIP> search(Map<String,Object> map);
    
	public int getRowCount();
	
    /**
	 * IP(域名数)TOP10
	 */
	public List<IPTopStatis>  domainCnt();
	/**
	 * 非法域名IPTOP10
	 */
	public List<IPTopStatis>  illegalcnt();
	/**
	 * IP域名总数态势
	 */
	public List<IPCntStatis>  situation(Map<String,Object> param);
	/**
	 * IP域名非法域名总数态势
	 */
	public List<IPCntStatis>  unsituation(Map<String,Object> param);
	
	/**
	 * IP域名总数
	 */
	public int  situationTotal();
	/**
	 * IP域名非法域名总数
	 */
	public int  unsituationTotal();
	/**
	 * IP平均挂域名态势
	 */
	public List<IPCntStatis>  avgsituation(Map<String,Object> param);
    
    
    
    
    
}