package com.gcexe.monitor.persistence.dao;

import java.util.List;
import java.util.Map;

import com.gcexe.monitor.persistence.entity.SysKey;
import com.gcexe.monitor.persistence.statistics.entity.KeyTopStatis;

public interface SysKeyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_key
	 * @mbggenerated  Wed Apr 25 19:22:56 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_key
	 * @mbggenerated  Wed Apr 25 19:22:56 CST 2018
	 */
	int insert(SysKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_key
	 * @mbggenerated  Wed Apr 25 19:22:56 CST 2018
	 */
	int insertSelective(SysKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_key
	 * @mbggenerated  Wed Apr 25 19:22:56 CST 2018
	 */
	SysKey selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_key
	 * @mbggenerated  Wed Apr 25 19:22:56 CST 2018
	 */
	int updateByPrimaryKeySelective(SysKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_key
	 * @mbggenerated  Wed Apr 25 19:22:56 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(SysKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_key
	 * @mbggenerated  Wed Apr 25 19:22:56 CST 2018
	 */
	int updateByPrimaryKey(SysKey record);

	List<SysKey> search(Map<String,Object> map);
	
	int getRowCount();
    
    /**
	 * 关键字排名TOP10
	 *
	 */
	public List<KeyTopStatis> keyorder();

	/**
	 * 传播站点排名TOP10
	 * 
	 */
	public List<KeyTopStatis> siteorder();

	/**
	 * 全球地图趋势分布
	 * 
	 */
	public int keyCount();
	public int urlCount();
    
	public List<KeyTopStatis> selectByKey(Map<String,Object> map);
	
	public List<KeyTopStatis> selectByUrl(Map<String,Object> map);
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}