package com.gcexe.monitor.persistence.entity;

import java.util.Date;

public class IPData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.ip_id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Integer ipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.ip_com
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String ipCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.ip
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.ip_domain
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String ipDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.record_no
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String recordNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.record_com
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String recordCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.record_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Date recordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.is_record
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Integer isRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.create_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.update_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.creator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.updator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_data.version
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.id
     *
     * @return the value of ip_data.id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.id
     *
     * @param id the value for ip_data.id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.ip_id
     *
     * @return the value of ip_data.ip_id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Integer getIpId() {
        return ipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.ip_id
     *
     * @param ipId the value for ip_data.ip_id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setIpId(Integer ipId) {
        this.ipId = ipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.ip_com
     *
     * @return the value of ip_data.ip_com
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getIpCom() {
        return ipCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.ip_com
     *
     * @param ipCom the value for ip_data.ip_com
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setIpCom(String ipCom) {
        this.ipCom = ipCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.ip
     *
     * @return the value of ip_data.ip
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.ip
     *
     * @param ip the value for ip_data.ip
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.ip_domain
     *
     * @return the value of ip_data.ip_domain
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getIpDomain() {
        return ipDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.ip_domain
     *
     * @param ipDomain the value for ip_data.ip_domain
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setIpDomain(String ipDomain) {
        this.ipDomain = ipDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.record_no
     *
     * @return the value of ip_data.record_no
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getRecordNo() {
        return recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.record_no
     *
     * @param recordNo the value for ip_data.record_no
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.record_com
     *
     * @return the value of ip_data.record_com
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getRecordCom() {
        return recordCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.record_com
     *
     * @param recordCom the value for ip_data.record_com
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setRecordCom(String recordCom) {
        this.recordCom = recordCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.record_time
     *
     * @return the value of ip_data.record_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.record_time
     *
     * @param recordTime the value for ip_data.record_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.is_record
     *
     * @return the value of ip_data.is_record
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Integer getIsRecord() {
        return isRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.is_record
     *
     * @param isRecord the value for ip_data.is_record
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setIsRecord(Integer isRecord) {
        this.isRecord = isRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.create_time
     *
     * @return the value of ip_data.create_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.create_time
     *
     * @param createTime the value for ip_data.create_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.update_time
     *
     * @return the value of ip_data.update_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.update_time
     *
     * @param updateTime the value for ip_data.update_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.creator
     *
     * @return the value of ip_data.creator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.creator
     *
     * @param creator the value for ip_data.creator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.updator
     *
     * @return the value of ip_data.updator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.updator
     *
     * @param updator the value for ip_data.updator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_data.version
     *
     * @return the value of ip_data.version
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_data.version
     *
     * @param version the value for ip_data.version
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}