package com.gcexe.monitor.persistence.entity;

import java.util.Date;

public class KeySearch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.key_id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Integer keyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.key_name
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String keyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.key_con
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String keyCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.title
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.url
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.address
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.create_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.update_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.creator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.updator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_search.version
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.id
     *
     * @return the value of key_search.id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.id
     *
     * @param id the value for key_search.id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.key_id
     *
     * @return the value of key_search.key_id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Integer getKeyId() {
        return keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.key_id
     *
     * @param keyId the value for key_search.key_id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setKeyId(Integer keyId) {
        this.keyId = keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.key_name
     *
     * @return the value of key_search.key_name
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.key_name
     *
     * @param keyName the value for key_search.key_name
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.key_con
     *
     * @return the value of key_search.key_con
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getKeyCon() {
        return keyCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.key_con
     *
     * @param keyCon the value for key_search.key_con
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setKeyCon(String keyCon) {
        this.keyCon = keyCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.title
     *
     * @return the value of key_search.title
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.title
     *
     * @param title the value for key_search.title
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.url
     *
     * @return the value of key_search.url
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.url
     *
     * @param url the value for key_search.url
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.address
     *
     * @return the value of key_search.address
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.address
     *
     * @param address the value for key_search.address
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.create_time
     *
     * @return the value of key_search.create_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.create_time
     *
     * @param createTime the value for key_search.create_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.update_time
     *
     * @return the value of key_search.update_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.update_time
     *
     * @param updateTime the value for key_search.update_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.creator
     *
     * @return the value of key_search.creator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.creator
     *
     * @param creator the value for key_search.creator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.updator
     *
     * @return the value of key_search.updator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.updator
     *
     * @param updator the value for key_search.updator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_search.version
     *
     * @return the value of key_search.version
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_search.version
     *
     * @param version the value for key_search.version
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}