package com.gcexe.monitor.persistence.entity;

import java.util.Date;

public class PicSearch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.pic_id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Integer picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.pic_name
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.pic_url
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.title
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.url
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.address
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.create_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.update_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.creator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.updator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_search.version
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.id
     *
     * @return the value of pic_search.id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.id
     *
     * @param id the value for pic_search.id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.pic_id
     *
     * @return the value of pic_search.pic_id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.pic_id
     *
     * @param picId the value for pic_search.pic_id
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.pic_name
     *
     * @return the value of pic_search.pic_name
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.pic_name
     *
     * @param picName the value for pic_search.pic_name
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setPicName(String picName) {
        this.picName = picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.pic_url
     *
     * @return the value of pic_search.pic_url
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.pic_url
     *
     * @param picUrl the value for pic_search.pic_url
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.title
     *
     * @return the value of pic_search.title
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.title
     *
     * @param title the value for pic_search.title
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.url
     *
     * @return the value of pic_search.url
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.url
     *
     * @param url the value for pic_search.url
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.address
     *
     * @return the value of pic_search.address
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.address
     *
     * @param address the value for pic_search.address
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.create_time
     *
     * @return the value of pic_search.create_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.create_time
     *
     * @param createTime the value for pic_search.create_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.update_time
     *
     * @return the value of pic_search.update_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.update_time
     *
     * @param updateTime the value for pic_search.update_time
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.creator
     *
     * @return the value of pic_search.creator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.creator
     *
     * @param creator the value for pic_search.creator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.updator
     *
     * @return the value of pic_search.updator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.updator
     *
     * @param updator the value for pic_search.updator
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_search.version
     *
     * @return the value of pic_search.version
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_search.version
     *
     * @param version the value for pic_search.version
     *
     * @mbggenerated Wed Apr 25 16:28:44 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}