package com.gcexe.monitor.persistence.entity;

import java.util.Date;

public class SysIP {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.id
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.ip_name
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private String ipName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.ip_com
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private String ipCom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.create_time
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.update_time
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.creator
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.updator
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private String updator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.icp_record
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private Integer icpRecord;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.gn_record
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private Integer gnRecord;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.monitor_rate_day
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private Integer monitorRateDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.monitor_rate_week
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private Integer monitorRateWeek;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.monitor_rate_month
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private Integer monitorRateMonth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.monitor_rate_year
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private Integer monitorRateYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.open_task
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private Integer openTask;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_ip.ip_list
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	private String ipList;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.id
	 * @return  the value of sys_ip.id
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.id
	 * @param id  the value for sys_ip.id
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.ip_name
	 * @return  the value of sys_ip.ip_name
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public String getIpName() {
		return ipName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.ip_name
	 * @param ipName  the value for sys_ip.ip_name
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setIpName(String ipName) {
		this.ipName = ipName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.ip_com
	 * @return  the value of sys_ip.ip_com
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public String getIpCom() {
		return ipCom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.ip_com
	 * @param ipCom  the value for sys_ip.ip_com
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setIpCom(String ipCom) {
		this.ipCom = ipCom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.create_time
	 * @return  the value of sys_ip.create_time
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.create_time
	 * @param createTime  the value for sys_ip.create_time
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.update_time
	 * @return  the value of sys_ip.update_time
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.update_time
	 * @param updateTime  the value for sys_ip.update_time
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.creator
	 * @return  the value of sys_ip.creator
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.creator
	 * @param creator  the value for sys_ip.creator
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.updator
	 * @return  the value of sys_ip.updator
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public String getUpdator() {
		return updator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.updator
	 * @param updator  the value for sys_ip.updator
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setUpdator(String updator) {
		this.updator = updator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.icp_record
	 * @return  the value of sys_ip.icp_record
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public Integer getIcpRecord() {
		return icpRecord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.icp_record
	 * @param icpRecord  the value for sys_ip.icp_record
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setIcpRecord(Integer icpRecord) {
		this.icpRecord = icpRecord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.gn_record
	 * @return  the value of sys_ip.gn_record
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public Integer getGnRecord() {
		return gnRecord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.gn_record
	 * @param gnRecord  the value for sys_ip.gn_record
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setGnRecord(Integer gnRecord) {
		this.gnRecord = gnRecord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.monitor_rate_day
	 * @return  the value of sys_ip.monitor_rate_day
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public Integer getMonitorRateDay() {
		return monitorRateDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.monitor_rate_day
	 * @param monitorRateDay  the value for sys_ip.monitor_rate_day
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setMonitorRateDay(Integer monitorRateDay) {
		this.monitorRateDay = monitorRateDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.monitor_rate_week
	 * @return  the value of sys_ip.monitor_rate_week
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public Integer getMonitorRateWeek() {
		return monitorRateWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.monitor_rate_week
	 * @param monitorRateWeek  the value for sys_ip.monitor_rate_week
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setMonitorRateWeek(Integer monitorRateWeek) {
		this.monitorRateWeek = monitorRateWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.monitor_rate_month
	 * @return  the value of sys_ip.monitor_rate_month
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public Integer getMonitorRateMonth() {
		return monitorRateMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.monitor_rate_month
	 * @param monitorRateMonth  the value for sys_ip.monitor_rate_month
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setMonitorRateMonth(Integer monitorRateMonth) {
		this.monitorRateMonth = monitorRateMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.monitor_rate_year
	 * @return  the value of sys_ip.monitor_rate_year
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public Integer getMonitorRateYear() {
		return monitorRateYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.monitor_rate_year
	 * @param monitorRateYear  the value for sys_ip.monitor_rate_year
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setMonitorRateYear(Integer monitorRateYear) {
		this.monitorRateYear = monitorRateYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.open_task
	 * @return  the value of sys_ip.open_task
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public Integer getOpenTask() {
		return openTask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.open_task
	 * @param openTask  the value for sys_ip.open_task
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setOpenTask(Integer openTask) {
		this.openTask = openTask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_ip.ip_list
	 * @return  the value of sys_ip.ip_list
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public String getIpList() {
		return ipList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_ip.ip_list
	 * @param ipList  the value for sys_ip.ip_list
	 * @mbggenerated  Wed Apr 25 19:21:46 CST 2018
	 */
	public void setIpList(String ipList) {
		this.ipList = ipList;
	}
}